#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
def Fibonacci_sequence(max_value):
    list = [1,2]
    len_of_list = len(list)
    while list[len_of_list-1]<max_value:
        newvalue = list[len_of_list-2] + list[len_of_list - 1]
        if(newvalue>max_value):
            break
        list.append(newvalue)
        len_of_list = len(list)
    total = 0
    for x in list:
        if(x%2 ==0):
            total += x
    print(total)

Fibonacci_sequence(4000000)