#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2

#if it is Pentagonal numbers return True
def is_Pentagonal_numbers(n):
    if (1+(24*n+1)**0.5) % 6 == 0:
        return True
    else:
        return False

#設置a和b去測試a-b,a+b是否為Pentagonal number
#因步伐會越來越大，因此若測試所有小於n=i的Pentagonal numbers
#找到的第一個答案即為最小的a-b
def main():
    i = 2
    loop = True
    while loop:
        for j in range(1, i):
            a = i * (3 * i - 1)/2
            b = j * (3 * j - 1)/2
            if is_Pentagonal_numbers(a + b) and is_Pentagonal_numbers(a - b):
                print(a - b)
                loop = False
                break
        i += 1

if __name__ == '__main__':
    main()